images:
  custom:
    # make sure to enclose owner in quotes, otherwise yaml will interpret it as a number
    owner: "099720109477"
    name: "ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-*"
    arch: x64
    platform: linux
    preinstall: |
      #!/bin/bash
      touch /tmp/preinstalled

runners:
  gofast:
    cpu: 4
    family: [c7a, c7i]
    image: ubuntu22-full-x64
