# The list of events the GitHub App subscribes to.
default_events:
 - workflow_job
 - meta

default_permissions:
  # required for registering runners
  administration: write
  # required to access config file
  single_file: write
  # required to report on errors
  issues: write
  # required to access collaborators and repository metadata
  metadata: read
  # Organization members and teams.
  # https://developer.github.com/v3/apps/permissions/#permission-on-members
  members: read
  # required to manage workflow runs
  actions: read

single_file_paths:
  - .github/runs-on.yml

name: runs-on

# Set to true when your GitHub App is available to the public or false when it is only accessible to the owner of the app.
public: false
